// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SolinAPI.Data;

#nullable disable

namespace SolinAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolinAPI.Models.AlertaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pet");

                    b.Property<bool>("Lido")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("b_lido");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("s_mensagem");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("s_severidade");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("s_titulo");

                    b.HasKey("Id");

                    b.ToTable("tb_alerta");
                });

            modelBuilder.Entity("SolinAPI.Models.EventoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_evento");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("s_descricao");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pet");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("s_origem");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("s_tipo");

                    b.HasKey("Id");

                    b.ToTable("tb_evento");
                });

            modelBuilder.Entity("SolinAPI.Models.HistoricoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("s_categoria");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_registro");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("s_descricao");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pet");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("s_titulo");

                    b.Property<string>("Veterinario")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("s_veterinario");

                    b.HasKey("Id");

                    b.ToTable("tb_historico");
                });

            modelBuilder.Entity("SolinAPI.Models.PetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_cadastro");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_nascimento");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("s_especie");

                    b.Property<int>("IdTutor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_tutor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("s_nome");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("n_peso");

                    b.Property<string>("Raca")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("s_raca");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("s_sexo");

                    b.HasKey("Id");

                    b.ToTable("tb_pet");
                });

            modelBuilder.Entity("SolinAPI.Models.TutorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("s_email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("s_nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("s_telefone");

                    b.HasKey("Id");

                    b.ToTable("tb_tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
